<StartScreen>

    BoxLayout:
        orientation: "vertical"
        size: root.width, root.height
        padding: 32
        spacing: 16

        Button:
            id: quali_label
            text: "Qualification steering wheel"
            font_size: 28
            on_release: root.quali_steering_clicked()

        Button:
            id: circuit_label
            text: "Qualification circuit comparison"
            font_size: 28
            on_release: root.quali_circuit_comp()